# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/weektimes', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Weektime. As you add validations to Weektime, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Weektime.create! valid_attributes
      get weektimes_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      weektime = Weektime.create! valid_attributes
      get weektime_url(weektime)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_weektime_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      weektime = Weektime.create! valid_attributes
      get edit_weektime_url(weektime)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Weektime' do
        expect do
          post weektimes_url, params: { weektime: valid_attributes }
        end.to change(Weektime, :count).by(1)
      end

      it 'redirects to the created weektime' do
        post weektimes_url, params: { weektime: valid_attributes }
        expect(response).to redirect_to(weektime_url(Weektime.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Weektime' do
        expect do
          post weektimes_url, params: { weektime: invalid_attributes }
        end.to change(Weektime, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post weektimes_url, params: { weektime: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested weektime' do
        weektime = Weektime.create! valid_attributes
        patch weektime_url(weektime), params: { weektime: new_attributes }
        weektime.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the weektime' do
        weektime = Weektime.create! valid_attributes
        patch weektime_url(weektime), params: { weektime: new_attributes }
        weektime.reload
        expect(response).to redirect_to(weektime_url(weektime))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        weektime = Weektime.create! valid_attributes
        patch weektime_url(weektime), params: { weektime: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested weektime' do
      weektime = Weektime.create! valid_attributes
      expect do
        delete weektime_url(weektime)
      end.to change(Weektime, :count).by(-1)
    end

    it 'redirects to the weektimes list' do
      weektime = Weektime.create! valid_attributes
      delete weektime_url(weektime)
      expect(response).to redirect_to(weektimes_url)
    end
  end
end
