# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/worktimes', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Worktime. As you add validations to Worktime, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Worktime.create! valid_attributes
      get worktimes_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      worktime = Worktime.create! valid_attributes
      get worktime_url(worktime)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_worktime_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      worktime = Worktime.create! valid_attributes
      get edit_worktime_url(worktime)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Worktime' do
        expect do
          post worktimes_url, params: { worktime: valid_attributes }
        end.to change(Worktime, :count).by(1)
      end

      it 'redirects to the created worktime' do
        post worktimes_url, params: { worktime: valid_attributes }
        expect(response).to redirect_to(worktime_url(Worktime.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Worktime' do
        expect do
          post worktimes_url, params: { worktime: invalid_attributes }
        end.to change(Worktime, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post worktimes_url, params: { worktime: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested worktime' do
        worktime = Worktime.create! valid_attributes
        patch worktime_url(worktime), params: { worktime: new_attributes }
        worktime.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the worktime' do
        worktime = Worktime.create! valid_attributes
        patch worktime_url(worktime), params: { worktime: new_attributes }
        worktime.reload
        expect(response).to redirect_to(worktime_url(worktime))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        worktime = Worktime.create! valid_attributes
        patch worktime_url(worktime), params: { worktime: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested worktime' do
      worktime = Worktime.create! valid_attributes
      expect do
        delete worktime_url(worktime)
      end.to change(Worktime, :count).by(-1)
    end

    it 'redirects to the worktimes list' do
      worktime = Worktime.create! valid_attributes
      delete worktime_url(worktime)
      expect(response).to redirect_to(worktimes_url)
    end
  end
end
